name: ubuntu

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build-a7c8f107ead0dc0f3715ed6191d43849616786f0
        run: cd && cargo install cross && git clone https://github.com/Hailey2022/geph4-exit && cd geph4-exit && cross build --release --locked --target x86_64-unknown-linux-musl
        
      - uses: actions/upload-artifact@v3
        with:
          name: geph4-exit
          path: ~/geph4-exit/target/x86_64-unknown-linux-musl/release/geph4-exit
